source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘10.2’
use_frameworks!

target 'again2007project' do
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON'
    pod 'DORM', '~> 0.1.3'
    use_frameworks!
end
